### ISSUE TITLE
Website Builder broken

### ISSUE THREAD

**Issue by Thore-Krug** [96boards/website#1332]
## Bug report

I never was able to sucessfully build the website using the provided script and Instructions.
 

### Description of the bug

Building of the Website is not sucessfullyl using ` Ubuntu 20.04 ` and ` Docker Docker version 19.03.8, build afacb8b7f0 `

After cloning the Repo and making the build script executable the srcipt starts to start but ends afetr a short while with the following Error. 

```bash
Container built by GitHub. Build reference: fb5077a
Multi-repo site detected; processing the required repositories ...
NSBREPO1: https://github.com/96boards/website.git
mktemp: failed to create directory via template ‘/srv/source/tmp.XXXXXXXXXX’: Permission denied
Cloning NSBREPO1
fatal: could not create work tree dir '': No such file or directory

```

Signed off by: Thore Krug opensource[at]thorekrug.de

**Comment by sgermanserrano** [comment]
@Thore-Krug are you running the script from within the `website` folder? i.e.
```
$ git clone https://github.com/96boards/website.git
$ cd website
$ JEKYLL_ACTION=serve ./build-site.sh
```
If you also have the `documentation` repo locally you can do 
```
$ JEKYLL_ACTION=serve NSBREPO2=/full/path/to/documentation/ ./build-site.sh
```
Can you try that?

**Comment by Thore-Krug** [comment]
@sgermanserrano  I was executing the Script from within the ` Website ` according to the README.md

Using your proposed method to include the documentation repository was from sucess. 


![96B-Website](https://user-images.githubusercontent.com/36414231/98598553-f4c99a80-22da-11eb-91fc-f4a473f0ad1b.png)

**Comment by pcolmer** [comment]
@Thore-Krug 

```
Container built by GitHub. Build reference: fb5077a
Multi-repo site detected; processing the required repositories ...
NSBREPO1: https://github.com/96boards/website.git
mktemp: failed to create directory via template ‘/srv/source/tmp.XXXXXXXXXX’: Permission denied
Cloning NSBREPO1
fatal: could not create work tree dir '': No such file or directory
```

Just to explain what is going on here ...

The website consists of two repositories - website and documentation. The build process supports two modes:

1. You tell the build process where the "other" repo is located on your computer or
2. The build process runs `git clone` to fetch the "missing" repo

The output that you provided from the build process *suggests* that you were actually in the documentation repo (and not the website repo) because it thinks it needs to close the website repo.

The process works by mounting the "current" repo into the Docker container as `/srv/source` then, if a repo needs to be cloned, it creates a temporary directory within `/srv/source`. You are getting a "Permission denied" error from that step - please check the permissions on your repo's directory. The build script does run the Docker container as the current user so, as long as *you* are able to create a directory in the repo's directory, it should work.

I'm happy to work with you to iron out the kinks in this if you are still having problems.

**Comment by Thore-Krug** [comment]
I spun up a new Virtual Machine to test if it was a Problem with my VM.  And it works fine in the new VM even if i just want to run the Website without Documentation.  Tested with Ubuntu 18.04 and 20.04 LTS.  I assume something must have been misconfigured on the old VM.  I wasnt able to reproduce the error again.  

Signed off by: Thore Krug opensource[at]thorekrug.de
